### ISSUE TITLE
showPassword not working

### ISSUE THREAD

**Issue by dekadentno** [apertureless/vue-password-strength-meter#12]
### Expected Behaviour
When I set the showPassword prop to true, the input type is not changing from "password" to "text".

### Actual Behavior
When I set the showPassword prop to true, the input type is always "password".

### Environment
- OS: macOS Sierra 20.12.6
- NPM version: 5.6.0
- vue.js version: 2.5.13
- vue-password-strength-meter version: 1.1.1

**Comment by apertureless** [comment]
Hm thats weird. 
Do you have `:toggle="true"` ? Because if you toggle over the internal icon and then try to set the prop it is not working. But in general the prop is working fine:

https://codesandbox.io/s/98w70xv714

**Comment by dekadentno** [comment]
Thank you for your response.
I am doing everything like you in the codesandbox example, but when clicking on the button, my input type is not changed to text, but the parent div with the "Password" class is toggling `show-password=true`. Very weird.

I assume there's a problem in my code structure or maybe another package is making this weird conflict. Will report here after I find out the problem.

Thanks.

**Comment by apertureless** [comment]
@dekadentno 

Eh, you wrote that you have version `1.1.1` ? 
That would explain it, as the show / hide password functions are introduced with version `1.2.0` https://github.com/apertureless/vue-password-strength-meter/releases

So updating to the current version `1.2.1` should fix it 🙈

**Comment by dekadentno** [comment]
Ah, updating to `1.2.1` fixed the problem. Almost lost my head with this.

Thanks a bunch @apertureless
