### ISSUE TITLE
Style not rendering whem the component is extended

### ISSUE THREAD

**Issue by ericcbarbosa** [apertureless/vue-password-strength-meter#14]
### Expected Behavior
When extended, the component should pass the styles for the one who's extending it.

### Actual Behavior
The component is loosing the css when extended, rendering the html and the tags, but not the style.

### Environment
- OS: Ubuntu 18.04 LTS
- NPM version: 5.7.1
- vue.js version: 2.5.16
- vue-password-strength-meter version: 1.2.1

**Comment by apertureless** [comment]
Not sure what you mean with extending.
Can you provide some jsfiddle / codepen for reproduction?
