### ISSUE TITLE
Pressing `enter` key on input toggles the password visibility

### ISSUE THREAD

**Issue by ericnilo** [apertureless/vue-password-strength-meter#21]
### Pre-requisite
`toggle` prop must be set to true

### Expected Behavior
User is typing a password and presses enter key, the input should not toggle the password visibility

### Actual Behavior
User is typing a password and presses enter key, the input is toggling the password visibility

This is an issue since whenever we want to submit the form, instead of submitting it, it just toggle the type.

### Environment
- NPM version: 6.0.1
- vue.js version: 2.5.16
- vue-password-strength-meter version: 1.3.0

**Comment by apertureless** [comment]
Hey @ericnilo 

I can not reproduce this behaviour.
Can you maybe provide a reproduction example?

For me if I enter a password and then press enter, nothing happens.
If I press tab the focus goes to the show/hide password button, then you can press enter to show and hide it.

However I could not reproduce it while the input got the focus.
