### ISSUE TITLE
Reverse "Show" / "Hide" labels

### ISSUE THREAD

**Issue by Bjornnyborg** [apertureless/vue-password-strength-meter#22]
### Expected Behavior
When i click the icon with label: "Hide password" i expect it to hide the password

### Actual Behavior
It's actually opposite, it shows password when i click the icon with title "Hide password" and vice versa.

### Solution
Reverse the "Hide"/"Show" title/labels

**Comment by apertureless** [comment]
Oh thanks! 
Fixed with https://github.com/apertureless/vue-password-strength-meter/commit/74789c3972f2c5578e96f3114552e45d80279f9e

Will be released soon!
