### ISSUE TITLE
Add $attrs directly to input field

### ISSUE THREAD

**Issue by apertureless** [apertureless/vue-password-strength-meter#25]
It might be a good idea to bind the `$attrs` directly to the input field.
This way we can get rid of some of the props and users could add aria labels and other attributes directly to the `<Password/>` element.

**Comment by khamer** [comment]
As best as I can tell, this is what you had in mind. Also simplifies the props, as you don't need explicit ones for autocomplete, disabled, required, name, id, etc.

**Comment by raybotha** [comment]
Is this working? It's a pretty useful feature

**Comment by apertureless** [comment]
Sorry, it got lost somehow. I merged it. 
Will update the readme and make a release.
