### ISSUE TITLE
`vue-cli` support (feature request)

### ISSUE THREAD

**Issue by longrunningprocess** [apertureless/vue-password-strength-meter#28]
### Expected Behavior
```
$ vue add vue-password-strength-meter zxcvbn
Installed!
```
All necessary dependencies would be added to the `package.json` according to https://cli.vuejs.org/guide/plugins-and-presets.html#plugins such as (https://github.com/vuetifyjs/vue-cli-plugin-vuetify, router or vuex)

### Actual Behavior
```
$ vue add vue-password-strength-meter zxcvbn

📦  Installing vue-cli-plugin-vue-password-strength-meter...

npm ERR! code E404
npm ERR! 404 Not Found: vue-cli-plugin-vue-password-strength-meter@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Clark/.npm/_logs/2018-11-14T15_59_59_465Z-debug.log
 ERROR  command failed: npm install --loglevel error -D vue-cli-plugin-vue-password-strength-meter
```

### Environment
- OS: `Darwin`
- NPM version: `6.4.1`
- vue.js version: `2.5.7`
- vue-cli version: `3.0.3`
- vue-password-strength-meter version: `@latest`

**Comment by apertureless** [comment]
Thanks for the feature-request. I had no time to look deeper into vue cli plugins. But it is on my list ✅

**Comment by wcjr** [comment]
Thanks!  And, fwiw, I abandoned this since it wasn't compatible with Vuetify so don't do it just for me in case that was ever a possibility ;-)

**Comment by apertureless** [comment]
Ah I see. If I find some time this weekend, I will merge the PRs and implement some of the feature requests. I guess then `vue-password` should be also working with vuetify.

**Comment by wcjr** [comment]
all of the styling and event-handling built into Vuetify's `v-text-field` would be lost on this component I believe.  Let me know if I'm wrong, I'd been happy to used yours :-)

**Comment by apertureless** [comment]
I see, thanks! You are right. 
However I am working on the `attrs` branch to bind the attributes and listeners directly to the input and not the root element. 

So with this, it should be possible to add for example the `@blur` event.

And with PR #19 it should be possible to add your own input field.
This should make `vue-password` way more flexible.

**Comment by wcjr** [comment]
That's a great idea, I've had to do the same for some of my "transparent wrappers" so it does work :-)
