### ISSUE TITLE
NPM Package not updated

### ISSUE THREAD

**Issue by xalunda** [apertureless/vue-password-strength-meter#31]
The latest package on [https://www.npmjs.com/package/vue-password-strength-meter](NPM) is 1.3.2.

Tried to force with @1.4.0 but _Couldn't find any versions for "vue-password-strength-meter" that matches "1.4.0"_

I wanted to use the new `:strength-meter-only="true"` feature

**Comment by apertureless** [comment]
Can you please check again?

**Comment by xalunda** [comment]
Hi @apertureless,

The version is now correctly available.
Thanks for your reactivity.

There is however a bug, should I create a new issue ?

Thanks

**Comment by apertureless** [comment]
Yeah feel free to create a new issue.
