### ISSUE TITLE
strength-meter-only - Empty payload on emitted event 

### ISSUE THREAD

**Issue by xalunda** [apertureless/vue-password-strength-meter#32]
I created a Vuetify text-field a my password input:
```
<v-text-field
    name="password"
    id="password"
    v-model="password"
    type="password"
    :rules="passwordRules"
    required
>
```
Appended the following
`<password v-model="password" :strength-meter-only="true"/>`

### Expected Behavior
The meter fill should be filled with the score

### Actual Behavior
The meter is not updated

### I did some digging
The event emitted by the component has an empty payload, caused by:
```
watch: {
  value (newValue) {
    if (this.strengthMeterOnly) {
      this.emitValue(newValue)
    }
  }
}
```

While `emitValue` expects two arguments
```
methods: {
  emitValue (type, value) {
    this.$emit(type, value)
    this.password = value
  }
}
```

Therefore setting `this.password` to `undefined`

### Environment
- OS: Macos 10.13.6 
- NPM version: 6.5.0
- vue.js version: 2.5.21
- vue-password-strength-meter version: 1.4.0

**Comment by apertureless** [comment]
Oh yeah, good catch.

I did refactor the `emitValue` method and added a type and forgot to change the watcher.
