### ISSUE TITLE
What is "/Users/jjuszczak/Projekte/Privat/"

### ISSUE THREAD

**Issue by sangdth** [apertureless/vue-password-strength-meter#33]
### Expected Behavior
No crash the Nuxt.

### Actual Behavior
Show really strange error.
````
[Vue warn]: Error in beforeCreate hook: "ReferenceError: document is not defined"

found in

---> <Password> at /Users/jjuszczak/Projekte/Privat/vue-password-strength-meter/src/components/PasswordStrengthMeter.vue
       <ElFormItem> at packages/form/src/form-item.vue
         <ElForm> at packages/form/src/form.vue
           <SignUpForm> at pages/signup.vue
             <Nuxt>
               <ElMain> at packages/main/src/main.vue
                 <ElContainer> at packages/container/src/main.vue
                   <Blank> at layouts/blank.vue
                     <Root>
````
My user account is `sangdth` and I have no idea is that user `jjuszczak` 

### Environment
- OS: Mac OS 10.14.3
- NPM version: 6.8.0
- vue.js version: Nuxtjs 2.4
- vue-password-strength-meter version: 1.4.1

**Comment by sangdth** [comment]
Found in your dist folder:
![screenshot 2019-02-27 at 1 21 45](https://user-images.githubusercontent.com/1083478/53453914-4611f780-3a2e-11e9-837a-611de323d730.png)

**Comment by apertureless** [comment]
It is actually my local path for the vue file. Seems that vue-loader might not strip it away for production. Will check the configs. Maybe I am missing a prod env somewhere.

However, this is totally unrelated to your issue / breaking. It is basically only for development purpose.

Your issue is that `document` is not available in the server side environment.

**Comment by sangdth** [comment]
@apertureless Ah. I think because I'm using Nuxt.js with server-side rendering, which caused this trouble. I think I will try to find a solution. Btw your work is nice. Cheer.

**Comment by hartwm** [comment]
> @apertureless Ah. I think because I'm using Nuxt.js with server-side rendering, which caused this trouble. I think I will try to find a solution. Btw your work is nice. Cheer.

did you ever find fix for this?

**Comment by sangdth** [comment]
Sry I stop working on that project.

**Comment by apertureless** [comment]
@hartwm what issue are you running in?

If you run into `document not defined` issue, you should try the `no-ssr`  or `client-only` component from nuxt. https://nuxtjs.org/api/components-client-only/

**Comment by guastallaigor** [comment]
I've manage to make it work using the `<client-only>` component in Nuxt.js. 
Thank you.
