### ISSUE TITLE
Support for zxcvbn user_inputs prop?

### ISSUE THREAD

**Issue by x42y** [apertureless/vue-password-strength-meter#34]
Unless I am mistaken there is currently no support for the zxcvbn `user_inputs` prop? I would love to see it supported, as currently if a user tries to register by entering an email, and then the same email in the password field, the password gets a high score.

**Comment by hallowcard13** [comment]
Hi @apertureless , can i work on this ?

**Comment by apertureless** [comment]
Hi @hallowcard13 
sure!

**Comment by hallowcard13** [comment]
Hi @apertureless @x42y , i have made a pr for the this feature request, found here #38

**Comment by apertureless** [comment]
Awesome thanks!
