### ISSUE TITLE
Make it possible to set id attribute for input element

### ISSUE THREAD

**Issue by datrinh** [apertureless/vue-password-strength-meter#48]
### Expected Behavior
Having an `id` prop to pass down to the `input[type="password]` element.

### Actual Behavior
No such property available (from the looks of it in the docs)

Maybe such a thing is possible and I merely didn't see it? This is required to use labels with the `for` attribute. Putting `id` on the password component itself, will result in both the wrapper AND the input to have the same ID, which is bad.

**Comment by apertureless** [comment]
Hey @datrinh 

this should actually work. You can bind all attributes to the `<Password>` component and they will appear on the input.

That the `id` appeared in the root element is a bug and should be fixed with the latest release.
