### ISSUE TITLE
Simple passwords returning strong?

### ISSUE THREAD

**Issue by bbashy** [apertureless/vue-password-strength-meter#7]
`password123` seems to be 7+ all green strength...

Seems a bit hit 'n' miss when typing fast or something?

**Comment by apertureless** [comment]
Hm not really. I tested it on the demo page, and `password123` gives you only a green 7 for the minimum characters. However the strength bar at the bottom is still low in the red area.

![](https://i.imgur.com/58qjb0t.png)

What you mean with hit 'n' miss? It is calculating the strength on each input

**Comment by bbashy** [comment]
Yeah can't seem to reproduce it now.

Never mind 🎉

**Comment by apertureless** [comment]
:v:
